# Generated by Django 4.1.4 on 2023-01-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusCapacityCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('End_Time', models.DateTimeField(auto_now_add=True)),
                ('In', models.IntegerField()),
                ('Out', models.IntegerField()),
                ('Total_Inside', models.IntegerField()),
            ],
        ),
    ]
