# Generated by Django 4.1.7 on 2023-02-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_occupancycount_delete_buscapacitycount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancycount',
            name='Bus_id',
            field=models.CharField(max_length=100),
        ),
    ]
